// Code generated by mockery v2.46.2. DO NOT EDIT.

package s3

import (
	context "context"

	minio "github.com/minio/minio-go/v7"
	mock "github.com/stretchr/testify/mock"
)

// MockS3Client is an autogenerated mock type for the S3Client type
type MockS3Client struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *MockS3Client) Get() *minio.Client {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *minio.Client
	if rf, ok := ret.Get(0).(func() *minio.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*minio.Client)
		}
	}

	return r0
}

// GetListOfObjectKeys provides a mock function with given fields: ctx, bucketName, options, regularPrefix
func (_m *MockS3Client) GetListOfObjectKeys(ctx context.Context, bucketName string, options *minio.ListObjectsOptions, regularPrefix string) ([]string, error) {
	ret := _m.Called(ctx, bucketName, options, regularPrefix)

	if len(ret) == 0 {
		panic("no return value specified for GetListOfObjectKeys")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *minio.ListObjectsOptions, string) ([]string, error)); ok {
		return rf(ctx, bucketName, options, regularPrefix)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *minio.ListObjectsOptions, string) []string); ok {
		r0 = rf(ctx, bucketName, options, regularPrefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *minio.ListObjectsOptions, string) error); ok {
		r1 = rf(ctx, bucketName, options, regularPrefix)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetObject provides a mock function with given fields: ctx, bucketName, objectPath, options
func (_m *MockS3Client) GetObject(ctx context.Context, bucketName string, objectPath string, options *minio.GetObjectOptions) (*minio.Object, error) {
	ret := _m.Called(ctx, bucketName, objectPath, options)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 *minio.Object
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *minio.GetObjectOptions) (*minio.Object, error)); ok {
		return rf(ctx, bucketName, objectPath, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *minio.GetObjectOptions) *minio.Object); ok {
		r0 = rf(ctx, bucketName, objectPath, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*minio.Object)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *minio.GetObjectOptions) error); ok {
		r1 = rf(ctx, bucketName, objectPath, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ping provides a mock function with given fields: ctx, bucketName
func (_m *MockS3Client) ping(ctx context.Context, bucketName string) error {
	ret := _m.Called(ctx, bucketName)

	if len(ret) == 0 {
		panic("no return value specified for ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, bucketName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockS3Client creates a new instance of MockS3Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3Client {
	mock := &MockS3Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
